services:
  homeassistant:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    environment:
      - TZ=${TZ}
      - HOST=${HOST}
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
