services:
  config-init:
    image: alpine:latest
    container_name: config-init
    user: "${UID}:${GID}"
    volumes:
      - ./scripts/config-files/:/input/
      - ./zigbee2mqtt/data/:/output/zigbee2mqtt/
      - ./mosquitto/config/:/output/mosquitto/
      - ./scripts/process-config.sh:/process-config.sh
    environment:
      - DEVICE_my_occupancy_sensor=${DEVICE_my_occupancy_sensor}
      - DEVICE_luz_sala_passagem=${DEVICE_luz_sala_passagem}
      - DEVICE_luz_sala_passagem_quartos=${DEVICE_luz_sala_passagem_quartos}
      - DEVICE_botao_sala=${DEVICE_botao_sala}
      - DEVICE_luz_quarto_trabalho=${DEVICE_luz_quarto_trabalho}
      - DEVICE_luz_quarto=${DEVICE_luz_quarto}
      - DEVICE_luz_quarto_paulo=${DEVICE_luz_quarto_paulo}
      - DEVICE_luz_quarto_thais=${DEVICE_luz_quarto_thais}
      - DEVICE_porta_esquerda_armario_paulo=${DEVICE_porta_esquerda_armario_paulo}
      - DEVICE_porta_direita_armario_paulo=${DEVICE_porta_direita_armario_paulo}
      - DEVICE_porta_esquerda_armario_thais=${DEVICE_porta_esquerda_armario_thais}
      - DEVICE_porta_direita_armario_thais=${DEVICE_porta_direita_armario_thais}
      - DEVICE_luz_armario_thais=${DEVICE_luz_armario_thais}
      - DEVICE_luz_armario_paulo=${DEVICE_luz_armario_paulo}
      - DEVICE_detector_fumaca_cozinha=${DEVICE_detector_fumaca_cozinha}
      - DEVICE_botao_sala_trabalho=${DEVICE_botao_sala_trabalho}
      - DEVICE_sensor_movimento=${DEVICE_sensor_movimento}
      - DEVICE_luz_cozinha=${DEVICE_luz_cozinha}
      - DEVICE_fechadura=${DEVICE_fechadura}
      - DEVICE_sensor_sacada=${DEVICE_sensor_sacada}
      - MQTT_ADVANCED_NETWORK_KEY=${MQTT_ADVANCED_NETWORK_KEY}
      - MQTT_ADVANCED_PAN_ID=${MQTT_ADVANCED_PAN_ID}
      - MQTT_ADVANCED_CHANNEL=${MQTT_ADVANCED_CHANNEL}
    command: ["/bin/sh", "/process-config.sh"]
    restart: "no"
      #  homeassistant:
      #    container_name: hass
      #    image: ghcr.io/home-assistant/home-assistant:stable
      #    user: "${UID}:${GID}"
      #    restart: always
      #    environment:
      #      - TZ=${TZ}
      #      - HOST=${HOST}
      #    volumes:
      #      - ./homeassistant:/config
      #      - /etc/localtime:/etc/localtime:ro
      #    privileged: true
      #    network_mode: host
      #    devices:
      #      - /dev/ttyAMA0:/dev/ttyAMA0
  mosquitto:
    image: eclipse-mosquitto:2
    user: "${UID}:${GID}"
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
  zigbee2mqtt:
    container_name: zigbee2mqtt
    user: "${UID}:${GID}"
    privileged: true
    restart: always
    image: koenkk/zigbee2mqtt:latest
    network_mode: host
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=${MQTT_HOST}
      - ZIGBEE2MQTT_CONFIG_MQTT_PORT=${MQTT_PORT}
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=${MQTT_USER}
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=${MQTT_PASS}
      - ZIGBEE2MQTT_CONFIG_FRONTEND_HOST=${HOST}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
        #      - /dev/ttyUSB0:/dev/ttyACM0
    depends_on:
      config-init:
        condition: service_completed_successfully
